batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- o3
data_dir: D:\Will_Git\Ozone_ML\Year2\Merged_Data\nh2
dataset: ozone_dataset
device: None
dynamic_inputs:
- u10
- v10
- r2
- sp
- t2m
- dswrf
- MAXUVV
epochs: 25
experiment_name: 24_missing_MAXDVV
head: regression
hidden_size: 20
initial_forget_bias: 3
learning_rate:
  0: 1e-2
  30: 5e-3
  40: 1e-3
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: RMSE
metrics:
- NSE
- RMSE
- Pearson-r
model: cudalstm
num_workers: 8
optimizer: Adam
output_activation: linear
output_dropout: 0.2
predict_last_n:
  1H: 1
run_dir: D:\Will_Git\Ozone_ML\forecast_runs
save_weights_every: 1
seq_length:
  1H: 24
static_attributes:
- NLCD
- pop_den
- orog
target_variables:
- o3
test_basin_file: D:\Will_Git\Ozone_ML\Year2\scripts_dir\neuralHydro\trainingSites.txt
test_end_date: 31/12/2023
test_start_date: 01/01/2023
train_basin_file: D:\Will_Git\Ozone_ML\Year2\scripts_dir\neuralHydro\trainingSites.txt
train_end_date: 31/12/2022
train_start_date: 01/01/2021
use_frequencies: 1H
validate_every: 5
validate_n_random_basins: 1
validation_basin_file: D:\Will_Git\Ozone_ML\Year2\scripts_dir\neuralHydro\trainingSites.txt
validation_end_date: 31/12/2023
validation_start_date: 01/01/2023
