xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    MAXDVV:
      dims: []
      attrs: {}
      data: 0.020680725574493408
    MAXUVV:
      dims: []
      attrs: {}
      data: 0.03444511070847511
    dswrf:
      dims: []
      attrs: {}
      data: 260.6692199707031
    o3:
      dims: []
      attrs: {}
      data: 14.079065322875977
    o3_6day:
      dims: []
      attrs: {}
      data: 14.08366584777832
    r2:
      dims: []
      attrs: {}
      data: 19.830291748046875
    sp:
      dims: []
      attrs: {}
      data: 2938.6630859375
    t2m:
      dims: []
      attrs: {}
      data: 7.837826728820801
    u10:
      dims: []
      attrs: {}
      data: 1.589723825454712
    v10:
      dims: []
      attrs: {}
      data: 1.8013476133346558
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    MAXDVV:
      dims: []
      attrs: {}
      data: 0.00798423308879137
    MAXUVV:
      dims: []
      attrs: {}
      data: -0.02443666011095047
    dswrf:
      dims: []
      attrs: {}
      data: 166.65415954589844
    o3:
      dims: []
      attrs: {}
      data: 39.27445602416992
    o3_6day:
      dims: []
      attrs: {}
      data: 39.278907775878906
    r2:
      dims: []
      attrs: {}
      data: 51.978904724121094
    sp:
      dims: []
      attrs: {}
      data: 81736.2421875
    t2m:
      dims: []
      attrs: {}
      data: 287.2480163574219
    u10:
      dims: []
      attrs: {}
      data: 0.009822704829275608
    v10:
      dims: []
      attrs: {}
      data: -0.1157863512635231
